[package]
name = "bluekompass"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui_extras = { version = "0.27.2", features = ["all_loaders"] }
egui_file = "0.17.0"
egui_plot = { version = "0.27.2", features = ["default"] }
image = "0.25.1"
